name: ci

on:
  - push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build

  deploy:
    # debugging을 위해 잠시 비활성화
    # if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - working-directory: public
        run: |
          cp ../CNAME ./
          git checkout -b gh-pages
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git add .
          git commit -m "Deploy blog for $GITHUB_SHA"
          git push -f
